#!/usr/bin/env python3
"""
Synthetic Data (SDG) Dataset Exporter for YOLOv8 & COCO Formats.
Converts Omniverse Replicator / standalone SDG outputs into standard
computer vision training datasets ready for Ultralytics YOLO or PyTorch/Torchvision.
"""

import argparse
import json
import os
import shutil
import sys
from typing import Dict, List, Tuple

CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
WORKSPACE_DIR = os.path.dirname(CURRENT_DIR)
if CURRENT_DIR not in sys.path:
    sys.path.insert(0, CURRENT_DIR)
if WORKSPACE_DIR not in sys.path:
    sys.path.insert(0, WORKSPACE_DIR)

SDG_DEFAULT_DIR = os.path.join(CURRENT_DIR, "_sdg_output")

CLASS_MAPPING = {
    "cube": 0,
    "sphere": 1,
    "cylinder": 2,
    "capsule": 3
}


def ensure_sdg_dataset(sdg_dir: str):
    """Ensures synthetic dataset annotations exist before export."""
    ann_file = os.path.join(sdg_dir, "dataset_annotations.json")
    if not os.path.exists(ann_file):
        print(f"[*] Annotations not found at {ann_file}. Automatically generating synthetic frames...")
        from generate_synthetic_dataset_standalone import generate_synthetic_dataset
        generate_synthetic_dataset(output_dir=sdg_dir, num_frames=5)


def export_yolo_format(sdg_dir: str, output_dir: str, split_ratio: float = 0.8) -> str:
    """Exports SDG frames into YOLOv8 dataset format with data.yaml."""
    ensure_sdg_dataset(sdg_dir)
    ann_file = os.path.join(sdg_dir, "dataset_annotations.json")

    with open(ann_file, "r") as f:
        data = json.load(f)

    frames = data.get("frames", [])
    if not frames:
        raise ValueError("No frames found in dataset annotations.")

    print(f"[*] Exporting {len(frames)} frames to YOLO format at: {output_dir}")

    # Directories
    train_img_dir = os.path.join(output_dir, "train", "images")
    train_lbl_dir = os.path.join(output_dir, "train", "labels")
    val_img_dir = os.path.join(output_dir, "val", "images")
    val_lbl_dir = os.path.join(output_dir, "val", "labels")

    for d in [train_img_dir, train_lbl_dir, val_img_dir, val_lbl_dir]:
        os.makedirs(d, exist_ok=True)

    num_train = max(1, int(len(frames) * split_ratio))

    for idx, frame in enumerate(frames):
        is_train = idx < num_train
        target_img_dir = train_img_dir if is_train else val_img_dir
        target_lbl_dir = train_lbl_dir if is_train else val_lbl_dir

        src_img = os.path.join(sdg_dir, frame["rgbImage"])
        img_name = frame["rgbImage"]
        dst_img = os.path.join(target_img_dir, img_name)

        if os.path.exists(src_img):
            shutil.copy2(src_img, dst_img)

        # Write YOLO label format (class x_center y_center width height) normalized [0, 1]
        img_w, img_h = frame["resolution"]
        lbl_file = os.path.join(target_lbl_dir, f"{os.path.splitext(img_name)[0]}.txt")

        with open(lbl_file, "w") as lf:
            for ann in frame.get("annotations", []):
                cls_name = ann.get("class", "cube").lower()
                cls_id = CLASS_MAPPING.get(cls_name, 0)
                box = ann["box2d"]  # [xmin, ymin, xmax, ymax]

                bx = (box[0] + box[2]) / 2.0 / img_w
                by = (box[1] + box[3]) / 2.0 / img_h
                bw = (box[2] - box[0]) / img_w
                bh = (box[3] - box[1]) / img_h

                lf.write(f"{cls_id} {bx:.6f} {by:.6f} {bw:.6f} {bh:.6f}\n")

    # Create data.yaml
    yaml_content = f"""# YOLOv8 Dataset Configuration generated by Omniverse SDG
path: {os.path.abspath(output_dir).replace('\\', '/')}
train: train/images
val: val/images

names:
  0: cube
  1: sphere
  2: cylinder
  3: capsule
"""
    with open(os.path.join(output_dir, "data.yaml"), "w") as yf:
        yf.write(yaml_content)

    print(f"[OK] YOLOv8 Dataset ready: {os.path.join(output_dir, 'data.yaml')}")
    return output_dir


def export_coco_format(sdg_dir: str, output_dir: str) -> str:
    """Exports SDG frames into COCO format with instances_train.json."""
    ensure_sdg_dataset(sdg_dir)
    ann_file = os.path.join(sdg_dir, "dataset_annotations.json")

    with open(ann_file, "r") as f:
        data = json.load(f)

    frames = data.get("frames", [])
    print(f"[*] Exporting {len(frames)} frames to COCO format at: {output_dir}")

    images_dir = os.path.join(output_dir, "images")
    ann_dir = os.path.join(output_dir, "annotations")
    os.makedirs(images_dir, exist_ok=True)
    os.makedirs(ann_dir, exist_ok=True)

    coco_data = {
        "info": {"description": "Omniverse Synthetic Dataset", "version": "1.0"},
        "categories": [
            {"id": 0, "name": "cube", "supercategory": "object"},
            {"id": 1, "name": "sphere", "supercategory": "object"},
            {"id": 2, "name": "cylinder", "supercategory": "object"},
            {"id": 3, "name": "capsule", "supercategory": "object"}
        ],
        "images": [],
        "annotations": []
    }

    ann_id = 1
    for img_id, frame in enumerate(frames, start=1):
        src_img = os.path.join(sdg_dir, frame["rgbImage"])
        dst_img = os.path.join(images_dir, frame["rgbImage"])
        if os.path.exists(src_img):
            shutil.copy2(src_img, dst_img)

        coco_data["images"].append({
            "id": img_id,
            "file_name": frame["rgbImage"],
            "width": frame["resolution"][0],
            "height": frame["resolution"][1]
        })

        for ann in frame.get("annotations", []):
            cls_name = ann.get("class", "cube").lower()
            cls_id = CLASS_MAPPING.get(cls_name, 0)
            box = ann["box2d"]  # [xmin, ymin, xmax, ymax]
            w = box[2] - box[0]
            h = box[3] - box[1]

            coco_data["annotations"].append({
                "id": ann_id,
                "image_id": img_id,
                "category_id": cls_id,
                "bbox": [box[0], box[1], w, h],
                "area": w * h,
                "segmentation": [[box[0], box[1], box[2], box[1], box[2], box[3], box[0], box[3]]],
                "iscrowd": 0
            })
            ann_id += 1

    coco_json_path = os.path.join(ann_dir, "instances_train.json")
    with open(coco_json_path, "w") as f:
        json.dump(coco_data, f, indent=2)

    print(f"[OK] COCO Dataset ready: {coco_json_path}")
    return output_dir


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Export SDG synthetic dataset to YOLO/COCO.")
    parser.add_argument("--format", "-f", choices=["yolo", "coco", "all"], default="all", help="Target format")
    parser.add_argument("--input", "-i", default=SDG_DEFAULT_DIR, help="Source SDG directory")
    parser.add_argument("--output", "-o", default=os.path.join(WORKSPACE_DIR, "replicator", "_exported_dataset"), help="Output directory")
    args = parser.parse_args()

    if args.format in ["yolo", "all"]:
        export_yolo_format(args.input, os.path.join(args.output, "yolo"))
    if args.format in ["coco", "all"]:
        export_coco_format(args.input, os.path.join(args.output, "coco"))
